/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Form Schema */
        get: operations["form_schema_api_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Location */
        post: operations["check_location_api_location_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hotspots */
        get: operations["list_hotspots_api_hotspots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotspot Meta */
        get: operations["hotspot_meta_api_hotspots_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nearby */
        get: operations["nearby_api_hotspots_nearby_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots/{hotspot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotspot Details */
        get: operations["hotspot_details_api_hotspots__hotspot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hotspots/along-route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Along Route */
        post: operations["along_route_api_hotspots_along_route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About */
        get: operations["about_api_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlongRouteOut
         * @example {
         *       "count": 2,
         *       "hotspots": [],
         *       "length_km": 4.2,
         *       "summary": {
         *         "collisions": 40,
         *         "fatal": 1,
         *         "hotspots": 2,
         *         "per_10_km": 95.2
         *       },
         *       "truncated": false
         *     }
         */
        AlongRouteOut: {
            /** Length Km */
            length_km: number;
            /** Count */
            count: number;
            /** Truncated */
            truncated: boolean;
            /** Hotspots */
            hotspots: components["schemas"]["RouteHotspotOut"][];
            summary: components["schemas"]["RouteSummary"];
        };
        /**
         * DetailsOut
         * @example {
         *       "hotspot": {
         *         "id": 1
         *       },
         *       "persistence": {
         *         "label": "Persistent",
         *         "rules": {},
         *         "years_present": 5
         *       },
         *       "profile": {
         *         "baseline_subset": "all",
         *         "months": [],
         *         "shares": [],
         *         "time_of_day": [],
         *         "years": []
         *       }
         *     }
         */
        DetailsOut: {
            hotspot: components["schemas"]["HotspotOut"];
            profile: components["schemas"]["ProfileOut"];
            persistence: components["schemas"]["PersistenceOut"];
        };
        /** FieldOption */
        FieldOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** FormField */
        FormField: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Required */
            required: boolean;
            /** Help */
            help: string | null;
            /** Options */
            options: components["schemas"]["FieldOption"][];
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Placeholder */
            placeholder: string | null;
        };
        /** FormGroup */
        FormGroup: {
            /** Title */
            title: string;
            /** Fields */
            fields: components["schemas"]["FormField"][];
            /** Widget */
            widget?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOk */
        HealthOk: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Model */
            model: string;
            /** Demo */
            demo: boolean;
            /** Warnings */
            warnings: string[];
            /** Coverage Grid */
            coverage_grid: string;
        };
        /**
         * HotspotListOut
         * @example {
         *       "count": 3,
         *       "hotspots": [],
         *       "slice": "All times",
         *       "subset": "severe",
         *       "total_matched": 3895,
         *       "truncated": true
         *     }
         */
        HotspotListOut: {
            /** Count */
            count: number;
            /** Subset */
            subset: string;
            /** Slice */
            slice: string;
            /** Total Matched */
            total_matched: number;
            /** Truncated */
            truncated: boolean;
            /** Hotspots */
            hotspots: components["schemas"]["HotspotOut"][];
        };
        /**
         * HotspotOut
         * @example {
         *       "collisions": 18,
         *       "fatal": 0,
         *       "id": 9031,
         *       "label": "LSOA E01033595",
         *       "latitude": 51.514775,
         *       "longitude": -0.141966,
         *       "persistence": "Persistent",
         *       "radius_m": 280,
         *       "serious": 18,
         *       "slice": "Evening Rush",
         *       "slight": 0,
         *       "subset": "severe",
         *       "years_present": 4
         *     }
         */
        HotspotOut: {
            /** Id */
            id: number;
            /** Subset */
            subset: string;
            /** Slice */
            slice: string;
            /** Month */
            month?: number | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Radius M */
            radius_m: number;
            /** Collisions */
            collisions: number;
            /** Fatal */
            fatal: number;
            /** Serious */
            serious: number;
            /** Slight */
            slight: number;
            /** Label */
            label?: string | null;
            /** Years Present */
            years_present?: number | null;
            /** Persistence */
            persistence?: string | null;
        };
        /** LocationCheckResponse */
        LocationCheckResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "covered" | "sparse" | "outside" | "unchecked";
            /** Nearest Km */
            nearest_km: number | null;
            /** Message */
            message: string | null;
            /** Allowed */
            allowed: boolean;
        };
        /** LocationOut */
        LocationOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "covered" | "sparse" | "outside" | "unchecked";
            /** Nearest Km */
            nearest_km: number | null;
        };
        /**
         * NearbyListOut
         * @example {
         *       "count": 1,
         *       "hotspots": [],
         *       "radius_m": 500
         *     }
         */
        NearbyListOut: {
            /** Count */
            count: number;
            /** Radius M */
            radius_m: number;
            /** Hotspots */
            hotspots: components["schemas"]["NearbyOut"][];
        };
        /**
         * NearbyOut
         * @example {
         *       "collisions": 18,
         *       "fatal": 0,
         *       "id": 9031,
         *       "label": "LSOA E01033595",
         *       "latitude": 51.514775,
         *       "longitude": -0.141966,
         *       "persistence": "Persistent",
         *       "radius_m": 280,
         *       "serious": 18,
         *       "slice": "Evening Rush",
         *       "slight": 0,
         *       "subset": "severe",
         *       "years_present": 4
         *     }
         */
        NearbyOut: {
            /** Id */
            id: number;
            /** Subset */
            subset: string;
            /** Slice */
            slice: string;
            /** Month */
            month?: number | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Radius M */
            radius_m: number;
            /** Collisions */
            collisions: number;
            /** Fatal */
            fatal: number;
            /** Serious */
            serious: number;
            /** Slight */
            slight: number;
            /** Label */
            label?: string | null;
            /** Years Present */
            years_present?: number | null;
            /** Persistence */
            persistence?: string | null;
            /** Distance M */
            distance_m: number;
            /**
             * Busiest Time
             * @description Time of day with the most collisions, or null without profiles
             */
            busiest_time?: string | null;
        };
        /** PersistenceOut */
        PersistenceOut: {
            /** Label */
            label: string | null;
            /** Years Present */
            years_present: number | null;
            /** Rules */
            rules: {
                [key: string]: string;
            };
        };
        /** PredictResponse */
        PredictResponse: {
            /** Severity Code */
            severity_code: number;
            /** Severity */
            severity: string;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Adjusted Scores */
            adjusted_scores: {
                [key: string]: number;
            };
            /**
             * Score Kind
             * @enum {string}
             */
            score_kind: "probability" | "score";
            /** Fatal Adjust */
            fatal_adjust: number;
            /** Adjust Mode */
            adjust_mode: string;
            /** Adjustment Note */
            adjustment_note: string;
            /** Left Blank */
            left_blank: string[];
            /** Warnings */
            warnings: string[];
            location: components["schemas"]["LocationOut"] | null;
        };
        /** ProfileMonth */
        ProfileMonth: {
            /** Month */
            month: number;
            /** Collisions */
            collisions: number;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Years */
            years: components["schemas"]["ProfileYear"][];
            /** Months */
            months: components["schemas"]["ProfileMonth"][];
            /** Time Of Day */
            time_of_day: components["schemas"]["ProfileSlice"][];
            /** Shares */
            shares: components["schemas"]["ProfileShare"][];
            /** Baseline Subset */
            baseline_subset: string;
        };
        /** ProfileShare */
        ProfileShare: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
            /** Here Pct */
            here_pct: number;
            /** Gb Pct */
            gb_pct: number;
        };
        /** ProfileSlice */
        ProfileSlice: {
            /** Slice */
            slice: string;
            /** Collisions */
            collisions: number;
        };
        /** ProfileYear */
        ProfileYear: {
            /** Year */
            year: number;
            /** Collisions */
            collisions: number;
        };
        /**
         * RouteHotspotOut
         * @example {
         *       "collisions": 18,
         *       "fatal": 0,
         *       "id": 9031,
         *       "label": "LSOA E01033595",
         *       "latitude": 51.514775,
         *       "longitude": -0.141966,
         *       "persistence": "Persistent",
         *       "radius_m": 280,
         *       "serious": 18,
         *       "slice": "Evening Rush",
         *       "slight": 0,
         *       "subset": "severe",
         *       "years_present": 4
         *     }
         */
        RouteHotspotOut: {
            /** Id */
            id: number;
            /** Subset */
            subset: string;
            /** Slice */
            slice: string;
            /** Month */
            month?: number | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Radius M */
            radius_m: number;
            /** Collisions */
            collisions: number;
            /** Fatal */
            fatal: number;
            /** Serious */
            serious: number;
            /** Slight */
            slight: number;
            /** Label */
            label?: string | null;
            /** Years Present */
            years_present?: number | null;
            /** Persistence */
            persistence?: string | null;
            /** Km From Start */
            km_from_start: number;
            /** Distance From Route M */
            distance_from_route_m: number;
        };
        /** RouteSummary */
        RouteSummary: {
            /** Hotspots */
            hotspots: number;
            /** Collisions */
            collisions: number;
            /** Fatal */
            fatal: number;
            /** Per 10 Km */
            per_10_km: number | null;
        };
        /** SchemaResponse */
        SchemaResponse: {
            /**
             * Loaded
             * @constant
             */
            loaded: true;
            /** Demo */
            demo: boolean;
            /** Model Name */
            model_name: string;
            /** Classes */
            classes: {
                [key: string]: string;
            };
            /**
             * Score Kind
             * @enum {string}
             */
            score_kind: "probability" | "score";
            /** Adjust Mode */
            adjust_mode: string;
            /** Fatal Adjust */
            fatal_adjust: number;
            /** Performance */
            performance: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
            /** Groups */
            groups: components["schemas"]["FormGroup"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOk"];
                };
            };
        };
    };
    form_schema_api_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaResponse"];
                };
            };
        };
    };
    check_location_api_location_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationCheckResponse"];
                };
            };
        };
    };
    predict_api_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
        };
    };
    list_hotspots_api_hotspots_get: {
        parameters: {
            query?: {
                subset?: string;
                slice?: string;
                min_collisions?: number;
                limit?: number;
                month?: number | null;
                persistence?: string;
                bbox?: string | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotspotListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hotspot_meta_api_hotspots_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    nearby_api_hotspots_nearby_get: {
        parameters: {
            query?: {
                latitude?: number | null;
                longitude?: number | null;
                radius_m?: number;
                subset?: string;
                slice?: string;
                month?: number | null;
                min_collisions?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hotspot_details_api_hotspots__hotspot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hotspot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    along_route_api_hotspots_along_route_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlongRouteOut"];
                };
            };
        };
    };
    about_api_about_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
